name: build_and_release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build_and_release:
    strategy:
      fail-fast: false
      matrix:
        go: [1.24]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Build and release ldap-cli
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Install go tools
        run: |
          go install golang.org/x/tools/gopls@latest && \
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Export Module Name
        id: export_module_name
        run: echo "MODULE_NAME=$(go mod edit -json | jq -r '.Module.Path')" >> "$GITHUB_OUTPUT"

      - name: Generate dynamic code samples and run linters
        run: go generate ./... && gofmt -s -d ./ && golangci-lint run -v

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out

      - name: Publish code coverage
        uses: qltysh/qlty-action/coverage@v2
        with:
          files: coverage.out
          add-prefix: ${{ steps.export_module_name.outputs.MODULE_NAME }}
          verbose: true
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}

      - name: Update code documentation
        run: curl -fsSL https://proxy.golang.org/${{ steps.export_module_name.outputs.MODULE_NAME }}/@v/${{ github.ref_name }}.info
